import React, { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="app">
      <header>
        <h1>Create a website Live tv</h1>
        <p>Generated by EditzwebZ</p>
      </header>
      
      <main>
        <div className="card">
          <button onClick={() => setCount(count + 1)}>
            Count: {count}
          </button>
        </div>
        
        <p className="description">
          Edit <code>src/App.jsx</code> to get started
        </p>
      </main>
    </div>
  )
}

export default App